### ISSUE TITLE
Delivery Buttons not match.

### ISSUE THREAD

**Issue by Deconta** [cheadrian/mergebot#2]
Hi. Cool project 👍
I'm trying to use the bot but the delivery buttons no longer work.  
Is there an update from the bot?

Screenshot:
![Screenshot_20240123-130114](https://github.com/cheadrian/mergebot/assets/84927009/627ac8d8-2e2e-46f5-8275-2b8687f63895)

**Comment by Deconta** [comment]
Thanks cheadrian, that works now. But for some reason the bot doesn't push my generators. Have I set something wrong?

![Uploading Screenshot_20240125-094522.png…]()

**Comment by Deconta** [comment]
Thanks cheadrian, that works now. But for some reason the bot doesn't push my generators. Have I set something wrong?

![Screenshot_20240125-094522](https://github.com/cheadrian/mergebot/assets/84927009/e07d3ac4-e386-4aa4-9895-bf195178add3)

**Comment by cheadrian** [comment]
That's looks correct. Check for any error on Termux terminal. If it does merge automatically, it should press the generators. Maybe try with a smaller number of generators, like 2,3,4.
